version: 2
jobs:
  build:
    working_directory: ~/myapp/angular-whishlist
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout:
          path: ~/myapp
      - restore_cache:
          key: angular-whishlist-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: angular-whishlist-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test -- --no-progress
      - run: npm run e2e -- --no-progress