version: 2
jobs:
  build:
    working_directory: ~/angular-whishlist
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: angular-whishlist-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: angular-whishlist-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test -- --single-run --no-progress --browser=ChromeHeadlessCI
      - run: npm run e2e -- --no-progress